### ISSUE TITLE
Serialize RDF

### ISSUE THREAD

**Issue by DylanVanAssche** [ozekik/lightrdf#10]
I was looking for a replacement for RDFLib for just parsing, do some BGP searching and write the new triples back.
It seems that LightRDF can handle parsing and BGP searching, but not serializing the RDF triples again to a file.

Are there any plans for this?

**Comment by dymil** [comment]
It seems like it wouldn't be too hard to combine this with RDFLib, i.e., grab the triples from LightRDF and then load them into an RDFLib store (as N-Triples syntax) and serialize from there. I'll play with it and upload a doc PR maybe. I think that'd still be reasonably fast just because RDFLib is _so_ slow at parsing – IIRC, several hours vs. several minutes once we're in the hundreds of millions of triples.

EDIT: Yeah, it seems like just parsing it into oxrdflib is pretty fast, given enough RAM.
```
g = Graph(store="Oxigraph")
g.parse(data = '\n'.join([f'{x[0]} {x[1]} {x[2]} .' for x in triples]), format='nt')
```
With 164K triples, this took 9.5s to run. Using the default `Memory` store, it took 3m41s, which does present unacceptable scaling IMO.

**Comment by ozekik** [comment]
Thank you for your suggestions. I intend to keep lightrdf focused on RDF parsing without complexity.
For serialization, I recommend [oxrdflib](https://github.com/oxigraph/oxrdflib) as @dymil mentioned or [pyoxigraph](https://pyoxigraph.readthedocs.io/en/stable/io.html) which is virtually the same.
